- client/src/components/Footer/Footer.jsx
> Componente FOOTER

- client/src/components/Card/Card.jsx
> Card - Thiago

- api/src/controllers/controllers.js
- client/src/components/Chart/Chart.jsx
- client/src/components/Chart/ChartOptions.js
Se modifica valor en controllers
> cambie un 1 de mierda y empezo a funcionar

- client/src/App.js
- client/src/components/Card/Card.jsx
- client/src/components/Home/Home.jsx
- client/yarn.lock
Created CARD component and added HOME component the cards list
> HOME - Thiago

- client/src/App.js
- client/src/components/Chart/Chart.jsx
- client/src/components/CoinCard/CoinCard.jsx
- client/src/components/Details/Details.jsx
- client/src/components/Home/Home.jsx
- client/src/components/LandingPage/LandingPage.jsx
- client/src/components/SearchBar/SearchBar.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
se corrige error de sintaxis en accion, archivo INDEX.JS
> Actions juan cruz

- client/src/components/CoinCard/CoinCard.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
- client/yarn.lock
funcion de agregar a favoritos
> favorites-rami

- client/package.json
- client/src/components/Metamask/Metamask.css
- client/src/components/Metamask/Metamask.jsx
Se agrego componente Metamask, junto con:
"@metamask/legacy-web3": "^2.0.0"
"web3-eth": "^1.8.1"
en el JSON de /client para que funcione..
> Se agrego componente Metamask

- client/src/components/Filter/Filter.jsx
- client/src/components/Home/Home.jsx
- client/src/components/SearchBar/SearchBar.jsx
el input del search se limpia con el boton de refresh
> REFRESH-SEARCH-facu

- client/src/components/CoinCard/CoinCard.jsx
> Star State

- api/index.js
- api/src/controllers/controllers.js
- api/src/db.js
- api/src/models/Review.js
- api/src/routes/coins.js
Cree el modelo Reviews, conecte en la tabla intermedia CoinsReviews las Reviews con la Coin a la que se la hacemos. Conecte en la tabla intermedia UserReviews la Review con el User que la hizo
> REVIEW-Thiago

- api/index.js
- api/src/controllers/controllers.js
- api/src/models/Coins.js
- api/src/routes/coins.js
Cree la ruta '/loadDb' para cargar la db de las coins. Cree el modelo Reviews y la tabla intermedia UserReviews para fijarse que User dejo cada Review y CoinReviews para ver que Reviews tiene cada Coin
> REVIEW-Backend-Thiago

- client/src/App.css
- client/src/components/LandingPage/LandingPage.jsx
> Boton LandingPage

- client/src/components/LandingPage/LandingPage.css
- client/src/components/LandingPage/LandingPage.jsx
> LandingPage css

- client/src/components/CoinCard/CoinCard.jsx
- client/src/components/Navbar/Navbar.jsx
- client/src/components/Navbar/Navbar.module.css
cambio de color de estrellas y navbar centrado
> FAVORITES-facu

- client/src/components/Chart/Chart.jsx
- client/src/components/Chart/Chart.module.css
- client/src/components/Details/Details.jsx
- client/src/components/Details/Details.module.css
Modificacion del estilo de las detail card
> DETAILSCARD-FACU

- client/src/components/Checkout/Payment.jsx
> Payment MP

- client/src/components/Checkout/Payment.jsx
> Payment return

- api/index.js
- client/src/components/Details/Details.jsx
- client/src/redux/actions/index.js
Creada la opcion de haceruna reseña con texto y numero desde el front, y que aparezca en cada moneda que buscamos el detalle
> REVIEW Create Front

- api/src/controllers/controllers.js
- api/src/models/Coins.js
- api/src/routes/coins.js
- client/src/components/AdminDashboardCoins/AdminDashboardCoins.jsx
Modificado modelo Coins: 
- id (agregado)
- name (modificado)
- disabled (agregado)
Modificado en controllers:
- loadCoinsiNDb() (modificado nombre de funcion)
parametros:
id: e.id (agregado)
name; e.name (e.id => e.name)
Modificado nombre de ruta en Coins:
routes / coins / get./loadCoinsInDb
> modificado el modelo Coins + loadCoinsInDb en controllers + ruta get./loadCoinsInDb

- client/src/App.js
- client/src/components/Comparative/Comparative.jsx
> Comparativo

- client/src/components/Calculator/Calculator.jsx
- client/src/components/Comparative/Comparative.jsx
> Modificaciones-Ro

- client/src/App.js
- client/src/components/FormLogin/FormLogin.jsx
- client/src/components/Home/Home.jsx
- client/src/components/Profile/Profile.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Cambios minimos con react-router en app.js
> Cambios minimos 

- client/src/components/Navbar/Navbar.jsx
- client/src/components/Profile/Profile.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> ARREGLANDO ERRORES

- client/src/components/FormLogin/FormLogin.module.css
- client/src/components/Profile/Profile.jsx
- client/src/redux/actions/index.js
> savechanges profile

- client/src/App.js
- client/src/components/FAQ/FAQ.jsx
mini cambios en el app y margin en el faq
> mini cambios-facurami

- api/src/controllers/controllers.js
- client/src/components/Profile/Profile.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> ramifacu-updateprofile

- api/src/controllers/controllers.js
- api/src/models/AdminChanges.js
- api/src/routes/users.js
- client/src/App.js
- client/src/components/AdminDashboardChanges/AdminDashboardChanges.jsx
- client/src/components/AdminDashboardCoins/AdminDashboardCoins.jsx
- client/src/components/AdminDashboardUsers/AdminDashboardUsers.jsx
Admin  Dashboard Changes es un tablero en el cual queda registro de todas las modificaciones que hace un admin.
Se crea ruta para visualizar tablero:
http://localhost:3000/adminchanges
Se agrega modelo en DB AdminChanges.js y rutas en User.js
Me mandé un true false, sepan disculpar xd
> Se agrega tablero Admin Changes.jsx

- client/src/components/Profile/Profile.jsx
> cloudi-ramifacu

- client/src/App.js
- client/src/components/Navbar/Navbar.jsx
> Dark theme onChange => onClick

- api/src/db.js
- api/src/firebase/firebaseConfig.js
- client/src/firebase/firebaseConfig.js
Se cambio la configuracion de firebase(con cuenta de gmail del proyecto) y database(en azure con gmail del proyecto)
**considerar los cambios en el archivo .env**
**DB_USER=postgres
DB_PASSWORD=p@ssw0rd
DB_HOST=cripto-srvr.postgres.database.azure.com**
> Cambio fb db ricardo

- client/src/App.js
- client/src/components/AdminDashboardChanges/AdminDashboardChanges.jsx
- client/src/components/CoinTarget/CoinTarget.jsx
- client/src/components/CoinTarget/CoinTarget.module.css
- client/src/components/LandingPag/LandingPag.jsx
- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.module.css
- client/src/components/Login/LoginBackground.css
- client/src/components/Navbar/Navbar.jsx
- client/src/components/Navbar/Navbar.module.css
- client/src/components/PanelAdmin/PanelAdmin.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/components/SignUp/SignUp.module.css
- client/src/components/SignUp/SignUpBackground.css
> admin, todo

- client/src/components/TrendingNew/TrendingNew.jsx
- client/src/components/TrendingNew/TrendingNew.module.css
- client/src/redux/actions/index.js
> mini cambios-ramifacu

- api/src/controllers/controllers.js
- api/src/db.js
- api/src/models/Comment.js
- api/src/routes/comments.js
- api/src/routes/index.js
- api/src/routes/warnings.js
- client/src/App.js
- client/src/components/CoinTarget/CoinTarget.jsx
- client/src/components/Details/Details.jsx
- client/src/components/Details/Details.module.css
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> el mejor equipo pa

- client/src/App.js
- client/src/components/About/About.jsx
- client/src/components/Developers/Developers.jsx
- client/src/components/FAQ/FAQ.jsx
- client/src/components/Footer/Footer.jsx
se completan los componente de devs y about
> About y Devs - Ricardo

- client/src/components/Calculator/Calculator.jsx
- client/src/components/Calculator/Calculator.module.css
- client/src/components/Exito/Exito.jsx
- client/src/components/Exito/Exito.module.css
cambios-calculadora y exito dino
> cambios-calculadora y exito dino

- client/src/App.js
- client/src/components/AdminDashboardWarnings/AdminDashboardWarnings.module.css
- client/src/components/PanelAdmin/PanelAdmin.jsx
- client/src/components/PanelUser/PanelUser.jsx
- client/src/components/PanelUser/PanelUser.module.css
- client/src/components/Profile/Profile.jsx
- client/src/components/Profile/Profile.module.css
- client/src/components/WarningAdmin/WarningAdmin.jsx
- client/src/components/WarningAdmin/WarningAdmin.module.css
> cambios y mas cambios

- client/src/components/Calculator/Calculator.jsx
- client/src/components/Home/Home.jsx
- client/src/components/LandingPag/LandingPag.jsx
- client/src/components/ShoppingCart/ShoppingCart.js
> localStorage

- client/src/components/Calculator/Calculator.jsx
- client/src/components/ShoppingCart/ShoppingCart.js
se agregan detalles al carrito (guest y user), faltan estilos..
> se agregan detalles al carrito (guest y user), faltan estilos..

- client/src/components/AdminDashboardTransactions/AdminDashboardTransactions.jsx
- client/src/components/TransactionAdmin/TransactionAdmin.jsx
- client/src/components/TransactionUser/TransactionUser.jsx
- client/src/components/WarningAdmin/WarningAdmin.jsx
- client/src/redux/reducer/index.js
> algunas alertas fuera

- client/src/components/Details/Details.jsx
- client/src/components/FormLogin/FormLogin.jsx
- client/src/components/PanelTransactions/PanelTransactions.jsx
- client/src/redux/actions/index.js
> alertas 2.0

- api/src/app.js
- client/src/components/AdminDashboardWarnings/AdminDashboardWarnings.jsx
- client/src/components/Calculator/Calculator.jsx
- client/src/components/Chart/Chart.jsx
- client/src/components/CoinTarget/CoinTarget.jsx
- client/src/components/CommentAdmin/CommentAdmin.jsx
- client/src/components/CommentTarget/CommentTarget.jsx
- client/src/components/Details/Details.jsx
- client/src/components/Exito/Exito.jsx
- client/src/components/FormLogin/FormLogin.jsx
- client/src/components/Home/Home.jsx
- client/src/components/Login/Login.jsx
- client/src/components/Navbar/Navbar.jsx
- client/src/components/Navbar/Switch.jsx
- client/src/components/PanelTransactions/PanelTransactions.jsx
- client/src/components/PanelUser/PanelUser.jsx
- client/src/components/Profile/Profile.jsx
- client/src/components/ProtectedAdmin/ProtectedAdmin.jsx
- client/src/components/ProtectedRoute/ProtectedRoute.jsx
- client/src/components/ShoppingCart/ShoppingCart.js
- client/src/components/SignUp/SignUp.jsx
> Deploy ricardo

- api/src/routes/users.js
Reverts PF-todopordoscriptos/PF-TodoX2Cripto#169
> Revert "updateURL"

- client/package.json
- package.json
Reverts PF-todopordoscriptos/PF-TodoX2Cripto#171
> Revert "update"

- api/package.json
- client/package.json
- client/src/components/About/About.jsx
- client/src/components/PanelUser/PanelUser.jsx
- client/src/components/PanelUser/PanelUser.module.css
- client/src/components/PanelWallet/PanelWallet.jsx
- client/src/components/PanelWallet/PanelWallet.module.css
- client/src/redux/actions/index.js
> wallet final

- api/src/routes/users.js
- client/src/components/Exito/Exito.jsx
- client/src/components/PanelUser/PanelUser.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> emails-ramifacu

- client/src/App.js
- client/src/components/Footer/Footer.jsx
- client/src/components/NewFAQ/NewFAQ.jsx
- client/src/components/NewFAQ/NewFAQ.module.css
> FAQ-ramifacu
